config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/zipcode'
  
  post 'zipcode' => 'home#zipcode'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'

    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=33620&distance=25&API_KEY=8549E168-A715-4772-B8A3-ED8A8B5BD904'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    #check for empty array
    if @output.empty?
      @final_output = 'Error'
    else 
      @final_output = @output[0]['AQI']
    end

    if @final_output == 'Error'
      @api_color = 'grey'
    elsif @final_output <= 50
      @api_color = 'green'
      @api_description = "Good (0 - 50) Air quality is considered satisfactory, and air pollution poses little or no risk."
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = 'yellow'
      @api_description = "Moderate (51 - 100) Air quality is acceptable; however, for some pollutants there may be a moderate health concern for a very small number of people who are unusually sensitive to air pollution."
    elsif @final_output >= 101 && @final_output <= 150
      @api_color = 'orange'
      @api_description = "Unhealthy for Sensitive Groups (101 - 150) 
      Although general public is not likely to be affected at this AQI range, people with lung disease, older adults and children are at a greater risk from exposure to ozone, whereas persons with heart and lung disease, older adults and children are at greater risk from the presence of particles in the air."
    elsif @final_output >= 151 && @final_output <= 200
      @api_color = 'red'
      @api_description = "Unhealthy (151 - 200) 
      Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects."
    elsif @final_output >= 201 && @final_output <= 300
      @api_color = 'purple'
      @api_description = "Very Unhealthy (201 - 300)
      Health alert: everyone may experience more serious health effects."
    elsif @final_output >= 301 && @final_output <= 500
      @api_color = 'maroon'
      @api_description = "Hazardous (301 - 500)
      Health warnings of emergency conditions. The entire population is more likely to be affected."

      

    end
  end

    def zipcode
      @zip = params[:zipcode]
      if params[:zipcode] == " "
        @zip = "Hey you forgot to enter a zipcode!"
      elsif params[:zipcode]
        #Do API stuff

          require 'net/http'
          require 'json'
      
          @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode='+ @zip +'&distance=25&API_KEY=8549E168-A715-4772-B8A3-ED8A8B5BD904'
          @uri = URI(@url)
          @response = Net::HTTP.get(@uri)
          @output = JSON.parse(@response)
      
          #check for empty array
          if @output.empty?
            @final_output = 'Error'
            @description = 'An error occured while trying to get your zipcode.'
          elsif !@output
            @final_output = 'Error'
            @description = 'An error occured while trying to get your zipcode.'
          else 
            @final_output = @output[0]['AQI']
            @description = 'This is the current air quality in your are, read the info below to learn more about what your ozone levels indicate.'
          end
      
          if @final_output == 'Error'
            @api_color = 'grey'
          elsif @final_output <= 50
            @api_color = 'green'
            @api_description = "Good (0 - 50) Air quality is considered satisfactory, and air pollution poses little or no risk."
          elsif @final_output >= 51 && @final_output <= 100
            @api_color = 'yellow'
            @api_description = "Moderate (51 - 100) Air quality is acceptable; however, for some pollutants there may be a moderate health concern for a very small number of people who are unusually sensitive to air pollution."
          elsif @final_output >= 101 && @final_output <= 150
            @api_color = 'orange'
            @api_description = "Unhealthy for Sensitive Groups (101 - 150) 
            Although general public is not likely to be affected at this AQI range, people with lung disease, older adults and children are at a greater risk from exposure to ozone, whereas persons with heart and lung disease, older adults and children are at greater risk from the presence of particles in the air."
          elsif @final_output >= 151 && @final_output <= 200
            @api_color = 'red'
            @api_description = "Unhealthy (151 - 200) 
            Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects."
          elsif @final_output >= 201 && @final_output <= 300
            @api_color = 'purple'
            @api_description = "Very Unhealthy (201 - 300)
            Health alert: everyone may experience more serious health effects."
          elsif @final_output >= 301 && @final_output <= 500
            @api_color = 'maroon'
            @api_description = "Hazardous (301 - 500)
            Health warnings of emergency conditions. The entire population is more likely to be affected."
          end
        end


    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "My Ozone", root_path, class: "navbar-brand" %> 
    <%= form_tag zipcode_path, :method => 'POST' do %>
    <div class="d-flex">
      <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode", class: "form-control me-2" %>
      <%= submit_tag 'Search', class: 'btn btn-outline-success' %>
    </div>
    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<div class="p-5 rounded-lg m-3 <%= @api_color %>">
    <h1 class="display-4"><%= @final_output %></h1>
    <p class="lead">This is the current air quality in your are, read the info below to learn more about what your ozone levels indicate.</p>
    <hr class="my-4">
    <p><%= @api_description %></p>
    <%# <a class="btn btn-secondary btn-lg" href="#" role="button">Learn more</a> %>
</div>
<br/>

app/views/home/zipcode.html.erb
<div class="p-5 rounded-lg m-3 <%= @api_color %>">
    <h1 class="display-4"><%= @final_output %></h1>
    <p class="lead"><%= @description %></p>
    <hr class="my-4">
    <p><%= @api_description %></p>
    <%# <a class="btn btn-secondary btn-lg" href="#" role="button">Learn more</a> %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
  </br>
  </br>
  <div class='container'>

    <%= yield %>
  <div/>
 

  </body>
</html>